# Generated by Django 2.0.2 on 2018-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='case_id_canlii',
            new_name='canlii_id',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='case_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='case_neutral_citation',
            new_name='neutral_citation',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='citing_case_id',
            new_name='citation_id',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='sentiment_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
