# Generated by Django 2.0.2 on 2018-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180224_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
